@echo off
REM ###########################################################################
REM Script generated by HP Fortify SCA Scan Wizard (c) HP Fortify 2011
REM Created on 2018/09/10 10:34:24
REM ###########################################################################
REM Generated for the following languages:
REM 	Java
REM 	Java Bytecode
REM 	Javascript
REM 	JSP J2EE
REM 	XML
REM ###########################################################################
REM DEBUG - if set to true, runs SCA in debug mode
REM SOURCEANALYZER - the name of the SCA executable
REM FPR - the name of analysis result file
REM BUILDID - the SCA build id
REM ARGFILE - the name of the argument file that's extracted and passed to SCA
REM BYTECODE_ARGFILE - the name of the argument file for Java Bytecode translation that's extracted and passed to SCA
REM MEMORY - the memory settings for SCA
REM LAUNCHERSWITCHES - the launcher settings that are used to invoke SCA
REM OLDFILENUMBER - this defines the file which contains the number of files within the project, it is automatically generated
REM FILENOMAXDIFF - this is the percentage of difference between the number of files which will trigger a warning by the script
REM ###########################################################################

set DEBUG=false
set SOURCEANALYZER=sourceanalyzer
set FPR="FortifyContol_Figures.fpr"
set BUILDID="Contol_Figures"
set ARGFILE="FortifyContol_Figures.bat.args"
set BYTECODE_ARGFILE="FortifyContol_Figures.bat.bytecode.args"
set MEMORY=-Xmx7279M -Xms400M -Xss24M 
set LAUNCHERSWITCHES=""
set OLDFILENUMBER=FortifyContol_Figures.bat.fileno
set FILENOMAXDIFF=10
set ENABLE_BYTECODE=false

set PROJECTROOT0="E:\Usuarios\inino\workspaceDemo\Contol_Figures"
IF NOT EXIST %PROJECTROOT0% (
   ECHO  ERROR: This script is being run on a different machine than it was
   ECHO         generated on or the targeted project has been moved. This script is 
   ECHO         configured to locate files at
   ECHO            %PROJECTROOT0%
   ECHO         Please modify the %%PROJECTROOT0%% variable found
   ECHO         at the top of this script to point to the corresponding directory
   ECHO         located on this machine.
   GOTO :FINISHED
)

IF %DEBUG%==true set LAUNCHERSWITCHES=-debug %LAUNCHERSWITCHES%
echo Extracting Arguments File


echo. >%ARGFILE%
echo. >%BYTECODE_ARGFILE%
SETLOCAL ENABLEDELAYEDEXPANSION
IF EXIST %0 (
   set SCAScriptFile=%0
) ELSE (
  set SCAScriptFile=%0.bat
)

set PROJECTROOT0=%PROJECTROOT0:)=^)%
FOR /f "delims=" %%a IN ('findstr /B /C:"REM ARGS" %SCAScriptFile%' ) DO (
   set argVal=%%a
   set argVal=!argVal:PROJECTROOT0_MARKER=%PROJECTROOT0:~1,-1%!
   echo !argVal:~9! >> %ARGFILE%
)
set PROJECTROOT0=%PROJECTROOT0:)=^)%
FOR /f "delims=" %%a IN ('findstr /B /C:"REM BYTECODE_ARGS" %SCAScriptFile%' ) DO (
   set ENABLE_BYTECODE=true
   set argVal=%%a
   set argVal=!argVal:PROJECTROOT0_MARKER=%PROJECTROOT0:~1,-1%!
   echo !argVal:~18! >> %BYTECODE_ARGFILE%
)
ENDLOCAL && set ENABLE_BYTECODE=%ENABLE_BYTECODE%

REM ###########################################################################
echo Cleaning previous scan artifacts
%SOURCEANALYZER% %MEMORY% %LAUNCHERSWITCHES% -b %BUILDID% -clean 
IF %ERRORLEVEL%==1 (
echo Sourceanalyzer failed, exiting
GOTO :FINISHED
)
REM ###########################################################################
echo Translating files
%SOURCEANALYZER% %MEMORY% %LAUNCHERSWITCHES% -b %BUILDID% @%ARGFILE%
IF %ERRORLEVEL%==1 (
echo Sourceanalyzer failed, exiting
GOTO :FINISHED
)
REM ###########################################################################
IF %ENABLE_BYTECODE%==true (
echo Translating Java bytecode files
%SOURCEANALYZER% %MEMORY% %LAUNCHERSWITCHES% -b %BUILDID% @%BYTECODE_ARGFILE%
IF %ERRORLEVEL%==1 (
echo Sourceanalyzer failed, exiting
GOTO :FINISHED
)
)
REM ###########################################################################
echo Testing Difference between Translations
SETLOCAL
FOR /F "delims=" %%A in ('%SOURCEANALYZER% -b %BUILDID% -show-files ^| findstr /R /N "^" ^| find /C ":" ') DO SET FILENUMBER=%%A
IF NOT EXIST %OLDFILENUMBER% (
	ECHO It appears to be the first time running this script, setting %OLDFILENUMBER% to %FILENUMBER%
	ECHO %FILENUMBER% > %OLDFILENUMBER%
	GOTO TESTENDED
)

FOR /F "delims=" %%i IN (%OLDFILENUMBER%) DO SET OLDFILENO=%%i
set /a DIFF=%OLDFILENO% * %FILENOMAXDIFF%
set /a DIFF /=  100
set /a MAX=%OLDFILENO% + %DIFF%
set /a MIN=%OLDFILENO% - %DIFF%

IF %FILENUMBER% LSS %MIN% set SHOWWARNING=true
IF %FILENUMBER% GTR %MAX% set SHOWWARNING=true

IF DEFINED SHOWWARNING (
	ECHO WARNING: The number of files has changed by over %FILENOMAXDIFF%%%, it is recommended 
	ECHO          that this script is regenerated with the ScanWizard
)
:TESTENDED
ENDLOCAL

REM ###########################################################################
echo Starting scan
%SOURCEANALYZER% %MEMORY% %LAUNCHERSWITCHES% -b %BUILDID% -scan -f %FPR%
IF %ERRORLEVEL%==1 (
echo Sourceanalyzer failed, exiting
GOTO :FINISHED
)
REM ###########################################################################
echo Finished
:FINISHED
REM ARGS "-cp"
REM ARGS "PROJECTROOT0_MARKER\WebContent\WEB-INF\lib\jxl.jar;PROJECTROOT0_MARKER\WebContent\WEB-INF\lib\poi-ooxml-3.15.jar;PROJECTROOT0_MARKER\WebContent\WEB-INF\lib\struts2-json-plugin-2.3.34.jar;PROJECTROOT0_MARKER\WebContent\WEB-INF\lib\commons-fileupload-1.3.2.jar;PROJECTROOT0_MARKER\WebContent\WEB-INF\lib\stax-api-1.0.1.jar"
REM ARGS "-cp"
REM ARGS "PROJECTROOT0_MARKER\WebContent\WEB-INF\lib\commons-io-2.2.jar;PROJECTROOT0_MARKER\WebContent\WEB-INF\lib\ojdbc5.jar;PROJECTROOT0_MARKER\WebContent\WEB-INF\lib\ognl-3.0.21.jar;PROJECTROOT0_MARKER\WebContent\WEB-INF\lib\commons-logging-1.1.3.jar;PROJECTROOT0_MARKER\WebContent\WEB-INF\lib\freemarker-2.3.22.jar"
REM ARGS "-cp"
REM ARGS "PROJECTROOT0_MARKER\WebContent\WEB-INF\lib\javax.servlet-3.0.jar;PROJECTROOT0_MARKER\build\classes;PROJECTROOT0_MARKER\WebContent\WEB-INF\lib\json-20140107.jar;PROJECTROOT0_MARKER\WebContent\WEB-INF\lib\xml-apis-1.4.01.jar;PROJECTROOT0_MARKER\WebContent\WEB-INF\lib\poi-scratchpad-3.15.jar"
REM ARGS "-cp"
REM ARGS "PROJECTROOT0_MARKER\WebContent\WEB-INF\lib\jackson-core-2.8.10.jar;PROJECTROOT0_MARKER\WebContent\WEB-INF\lib\gson-2.2.4.jar;PROJECTROOT0_MARKER\WebContent\WEB-INF\lib\axis.jar;PROJECTROOT0_MARKER\WebContent\WEB-INF\lib\joda-time-2.0.jar;PROJECTROOT0_MARKER\WebContent\WEB-INF\lib\struts2-core-2.3.34.jar"
REM ARGS "-cp"
REM ARGS "PROJECTROOT0_MARKER\WebContent\WEB-INF\lib\mybatis-3.3.0-SNAPSHOT.jar;PROJECTROOT0_MARKER\WebContent\WEB-INF\lib\commons-discovery-0.2.jar;PROJECTROOT0_MARKER\WebContent\WEB-INF\lib\curvesapi-1.04.jar;PROJECTROOT0_MARKER\WebContent\WEB-INF\lib\xerces2-xsd11-2.11.1.jar;PROJECTROOT0_MARKER\WebContent\WEB-INF\lib\javassist-3.11.0.GA.jar"
REM ARGS "-cp"
REM ARGS "PROJECTROOT0_MARKER\WebContent\WEB-INF\lib\commons-collections4-4.1.jar;PROJECTROOT0_MARKER\WebContent\WEB-INF\lib\xmlbeans-2.6.0.jar;PROJECTROOT0_MARKER\WebContent\WEB-INF\lib\log4j-1.2.17.jar;PROJECTROOT0_MARKER\WebContent\WEB-INF\lib\xwork-core-2.3.34.jar;PROJECTROOT0_MARKER\WebContent\WEB-INF\lib\poi-excelant-3.15.jar"
REM ARGS "-cp"
REM ARGS "PROJECTROOT0_MARKER\WebContent\WEB-INF\lib\saaj.jar;PROJECTROOT0_MARKER\WebContent\WEB-INF\lib\commons-net-3.3.jar;PROJECTROOT0_MARKER\WebContent\WEB-INF\lib\AesEncrypter.jar;PROJECTROOT0_MARKER\WebContent\WEB-INF\lib\commons-lang3-3.2.jar;PROJECTROOT0_MARKER\WebContent\WEB-INF\lib\wsdl4j.jar"
REM ARGS "-cp"
REM ARGS "PROJECTROOT0_MARKER\WebContent\WEB-INF\lib\poi-3.15.jar;PROJECTROOT0_MARKER\WebContent\WEB-INF\lib\xml-resolver-1.2.jar;PROJECTROOT0_MARKER\WebContent\WEB-INF\lib\jaxrpc.jar;PROJECTROOT0_MARKER\WebContent\WEB-INF\lib\poi-ooxml-schemas-3.15.jar;PROJECTROOT0_MARKER\WebContent\WEB-INF\lib\servlet.jar"
REM ARGS "-source"
REM ARGS "1.6"
REM ARGS "-exclude" "PROJECTROOT0_MARKER\**\*.jar"
REM ARGS "-exclude" "PROJECTROOT0_MARKER\**\*.class"
REM ARGS "PROJECTROOT0_MARKER"
